library(shiny)
library(spsurvey)
library(Hmisc)
library(shinyjs)
library(shinythemes)
library(shinybusy)
library(shinyhelper)
library(ggplot2)
library(ggridges)
library(stringr)
library(shinyBS)
library(dplyr)
library(DT)

# options(shiny.maxRequestSize = 20*1024^2) #Allows an upload of up to 20mb. 
options(scipen = 100)
